name: Linux

on:
  workflow_call:

jobs:
  build:
    env:
      MILODY_TARGET_OS: "linux"
      MILODY_TARGET_ARCH: "amd64"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 17
          platform: x64
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Meson
        run: pip3 install meson

      - name: Setup Environment Requirement
        run: |
          sudo apt-get install -y ninja-build nasm xorg-dev libasound2-dev

      - name: Run CMake configuration for Game Library
        run: |
          cmake -S . -B build_game \
          -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DMILODY_ENABLE_CLI=OFF \
          -DMILODY_ENABLE_TESTS=OFF \
          -DMILODY_BUILD_SHARED_LIBS=ON \
          -DCMAKE_INSTALL_PREFIX=./milody-game

      - name: Build Game Library
        run: cmake --build build_game --target install

      - name: Package Game Library
        run: tar -czvf milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}.tar.gz milody-game

      - name: Upload artifact Game
        uses: actions/upload-artifact@v4
        with:
          name: milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}
          path: milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}.tar.gz
          retention-days: 30
