name: Android

on:
  workflow_call:

jobs:
  build:
    env:
      MILODY_TARGET_OS: "android"
      MILODY_TARGET_ARCH: "arm64"
    runs-on: ubuntu-latest
    steps:
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23c
          add-to-path: true

      - name: Set up ANDROID_NDK_HOME
        run: echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Meson
        run: pip3 install meson

      - name: Setup Environment Requirement
        run: |
          sudo apt-get install -y ninja-build nasm xorg-dev

      - name: Run CMake configuration for Game Library
        run: |
          cmake -S . -B build_game -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DMILODY_ENABLE_CLI=OFF \
          -DMILODY_ENABLE_TESTS=OFF \
          -DMILODY_BUILD_SHARED_LIBS=ON \
          -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake" \
          -DCMAKE_SYSTEM_NAME=Android \
          -DANDROID_ABI=arm64-v8a \
          -DCMAKE_ANDROID_NDK="${ANDROID_NDK_HOME}" \
          -DANDROID_PLATFORM=android-23 \
          -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF \
          -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
          -DCMAKE_INSTALL_PREFIX=./milody-game

      - name: Build Game Library
        run: cmake --build build_game --target install

      - name: Package Game Library
        run: tar -czvf milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}.tar.gz milody-game

      - name: Upload artifact Game
        uses: actions/upload-artifact@v4
        with:
          name: milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}
          path: milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}.tar.gz
          retention-days: 30
