name: Formal merging and release

on:
  push:
    branches:
      #      - dev/feature*
      - master
      - release/*
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# 根据不同的构建目标分成多个job，最后统一由一个job上传到Release
jobs:
  #####################################
  # 构建
  # 受限于github action本身，无法用matrix来简化

  build-windows-amd64:
    name: Windows amd64
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  build-linux-amd64:
    name: Linux amd64
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  build-android-arm64:
    name: Android arm64
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  build-macos-arm64:
    name: MacOS arm64
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  build-ios-arm64:
    name: iOS arm64
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit

  #####################################
  # 重新打包
  repackage:
    needs: [ build-windows-amd64, build-linux-amd64, build-macos-arm64, build-android-arm64, build-ios-arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Repackage artifacts
        run: |
          mkdir -p milody-all-platforms/{Android,iOS,Linux,MacOS,Windows}
          
          # Android
          mkdir -p milody-all-platforms/Android/arm64-v8a-game
          tar -xzvf downloaded-artifacts/milody-game-android-arm64/milody-game-android-arm64.tar.gz -C milody-all-platforms/Android/arm64-v8a-game --strip-components=2 milody-game/lib/libMilody.so
          
          # iOS
          mkdir -p milody-all-platforms/iOS
          tar -xzvf downloaded-artifacts/milody-game-ios-arm64/milody-game-ios-arm64.tar.gz -C milody-all-platforms/iOS --strip-components=2 milody-game/lib/Milody.framework
          
          # Linux
          mkdir -p milody-all-platforms/Linux/amd64-game
          tar -xzvf downloaded-artifacts/milody-game-linux-amd64/milody-game-linux-amd64.tar.gz -C milody-all-platforms/Linux/amd64-game --strip-components=2 milody-game/lib/libMilody.so
          
          # MacOS
          mkdir -p milody-all-platforms/MacOS/aarch64-game
          tar -xzvf downloaded-artifacts/milody-game-macos-arm64/milody-game-macos-arm64.tar.gz -C milody-all-platforms/MacOS/aarch64-game --strip-components=2 milody-game/lib/libMilody.dylib
          
          # Windows
          mkdir -p milody-all-platforms/Windows/amd64-game
          unzip -j downloaded-artifacts/milody-game-windows-amd64/milody-game-windows-amd64.zip 'milody-game/bin/libMilody.dll' -d milody-all-platforms/Windows/amd64-game
          
          # Create the final package
          tar -czvf milody-all-platforms.tar.gz milody-all-platforms

      - name: Upload milody-all-platforms artifact
        uses: actions/upload-artifact@v4
        with:
          name: milody-all-platforms
          path: milody-all-platforms.tar.gz
          retention-days: 30

  #####################################
  # 部署
  deploy:
    needs: repackage
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            downloaded-artifacts/milody-game-windows-amd64/milody-game-windows-amd64.zip
            downloaded-artifacts/milody-game-linux-amd64/milody-game-linux-amd64.tar.gz
            downloaded-artifacts/milody-game-macos-arm64/milody-game-macos-arm64.tar.gz
            downloaded-artifacts/milody-game-android-arm64/milody-game-android-arm64.tar.gz
            downloaded-artifacts/milody-game-ios-arm64/milody-game-ios-arm64.tar.gz
            downloaded-artifacts/milody-all-platforms/milody-all-platforms.tar.gz
          name: Release ${{ github.ref_name }}
          body: Release of ${{ github.ref_name }}
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
